/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mariomakerv01;
import Clases.Objetos;
import Clases.ListaObjetos;
/**
 *
 * @author Luis Locon
 */
public class jfrmobjetosimg extends javax.swing.JFrame {

    ListaObjetos listobj = new ListaObjetos();
    int tamaño = 0;
    
    public jfrmobjetosimg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblimg_mario = new javax.swing.JLabel();
        lblimg_goomba = new javax.swing.JLabel();
        lblimg_koopa = new javax.swing.JLabel();
        lblimg_castle = new javax.swing.JLabel();
        lblimg_brick = new javax.swing.JLabel();
        lblimg_quest = new javax.swing.JLabel();
        jbtaddmario = new javax.swing.JButton();
        jbtaddkoopa = new javax.swing.JButton();
        jbtaddgoomba = new javax.swing.JButton();
        jbtquestb = new javax.swing.JButton();
        jbtaddbrick = new javax.swing.JButton();
        jbtcastle = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbarramenu_objt = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmitem_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cargar Objetos");
        setAlwaysOnTop(true);

        lblimg_mario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Retro-Mario-icon_peqe.png"))); // NOI18N

        lblimg_goomba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/goomba64.png"))); // NOI18N

        lblimg_koopa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/koopa_smb3_1.png"))); // NOI18N

        lblimg_castle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/castle.PNG"))); // NOI18N

        lblimg_brick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/brick_block64.gif"))); // NOI18N
        lblimg_brick.setToolTipText("");

        lblimg_quest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Retro Question Block_64.png"))); // NOI18N

        jbtaddmario.setText("Agregar");
        jbtaddmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtaddmarioActionPerformed(evt);
            }
        });

        jbtaddkoopa.setText("Agregar");
        jbtaddkoopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtaddkoopaActionPerformed(evt);
            }
        });

        jbtaddgoomba.setText("Agregar");
        jbtaddgoomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtaddgoombaActionPerformed(evt);
            }
        });

        jbtquestb.setText("Agregar");
        jbtquestb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtquestbActionPerformed(evt);
            }
        });

        jbtaddbrick.setText("Agregar");
        jbtaddbrick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtaddbrickActionPerformed(evt);
            }
        });

        jbtcastle.setText("Agregar");
        jbtcastle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtcastleActionPerformed(evt);
            }
        });

        jButton1.setText("print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jmitem_salir.setText("Salir");
        jmitem_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitem_salirActionPerformed(evt);
            }
        });
        jMenu1.add(jmitem_salir);

        jbarramenu_objt.add(jMenu1);

        setJMenuBar(jbarramenu_objt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblimg_castle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblimg_brick)
                            .addComponent(jbtaddbrick))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(62, 62, 62))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtaddmario)
                            .addComponent(lblimg_mario))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblimg_goomba)
                            .addComponent(jbtaddgoomba))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblimg_koopa)
                            .addComponent(jbtaddkoopa))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtquestb)
                            .addComponent(lblimg_quest)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jbtcastle)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblimg_quest)
                    .addComponent(lblimg_goomba)
                    .addComponent(lblimg_koopa)
                    .addComponent(lblimg_mario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtaddmario)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtaddgoomba)
                        .addComponent(jbtaddkoopa)
                        .addComponent(jbtquestb)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblimg_castle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtcastle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblimg_brick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtaddbrick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(37, 37, 37))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmitem_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitem_salirActionPerformed
            this.dispose();
    }//GEN-LAST:event_jmitem_salirActionPerformed

    private void jbtaddmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtaddmarioActionPerformed
                int numeroimg = 6 ;
                String nombreimg ="Mario" ;
            
            
                listobj.agregarObjeto(nombreimg, numeroimg);
                javax.swing.JOptionPane.showMessageDialog(null,"Se agrego Objeto");
                tamaño++;
         
    }//GEN-LAST:event_jbtaddmarioActionPerformed

    private void jbtaddgoombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtaddgoombaActionPerformed
        int numeroimg = 2 ;
                String nombreimg ="Goomba" ;
           
                listobj.agregarObjeto(nombreimg, numeroimg);
                javax.swing.JOptionPane.showMessageDialog(null,"Se agrego Objeto");
    }//GEN-LAST:event_jbtaddgoombaActionPerformed

    private void jbtaddkoopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtaddkoopaActionPerformed
                int numeroimg = 3 ;
                String nombreimg ="Koopa" ;
            
                listobj.agregarObjeto(nombreimg, numeroimg);
                javax.swing.JOptionPane.showMessageDialog(null,"Se agrego Objeto");
    }//GEN-LAST:event_jbtaddkoopaActionPerformed

    private void jbtquestbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtquestbActionPerformed
                int numeroimg = 4 ;
                String nombreimg ="Bloque Bono" ;
            
                listobj.agregarObjeto(nombreimg, numeroimg);
                javax.swing.JOptionPane.showMessageDialog(null,"Se agrego Objeto");
                tamaño++;
    }//GEN-LAST:event_jbtquestbActionPerformed

    private void jbtcastleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtcastleActionPerformed
                int numeroimg = 5 ;
                String nombreimg ="Castillo" ;
            
            
                listobj.agregarObjeto(nombreimg, numeroimg);
                javax.swing.JOptionPane.showMessageDialog(null,"Se agrego Objeto");
                tamaño++;
    }//GEN-LAST:event_jbtcastleActionPerformed

    private void jbtaddbrickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtaddbrickActionPerformed
                int numeroimg = 1 ;
                String nombreimg ="Bloque" ;
            
                listobj.agregarObjeto(nombreimg, numeroimg);
                javax.swing.JOptionPane.showMessageDialog(null,"Se agrego Objeto");
                tamaño++;
    }//GEN-LAST:event_jbtaddbrickActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        imprimir();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmobjetosimg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmobjetosimg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmobjetosimg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmobjetosimg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmobjetosimg().setVisible(true);
            }
        });
    }
    
    public void imprimir(){
        if (tamaño!=0){
            Objetos temp = ListaObjetos.cabeza;
            String str= "";
            for(int i = 0; i < this.tamaño; i++){
                str = str + temp.getNombre() + "\n";
                temp.getSig();
            }
            
            
            System.out.print(str);
        }
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jbarramenu_objt;
    private javax.swing.JButton jbtaddbrick;
    private javax.swing.JButton jbtaddgoomba;
    private javax.swing.JButton jbtaddkoopa;
    private javax.swing.JButton jbtaddmario;
    private javax.swing.JButton jbtcastle;
    private javax.swing.JButton jbtquestb;
    private javax.swing.JMenuItem jmitem_salir;
    private javax.swing.JLabel lblimg_brick;
    private javax.swing.JLabel lblimg_castle;
    private javax.swing.JLabel lblimg_goomba;
    private javax.swing.JLabel lblimg_koopa;
    private javax.swing.JLabel lblimg_mario;
    private javax.swing.JLabel lblimg_quest;
    // End of variables declaration//GEN-END:variables
}
